#http://blog.pgxn.org/post/4783001135/extension-makefiles pg makefiles

EXTENSION = <%=ext_name%>
EXTVERSION = $(shell grep default_version $(EXTENSION).control | \
                sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")
PG_CONFIG ?= pg_config

DATA = $(wildcard *--*.sql)
PGXS := $(shell $(PG_CONFIG) --pgxs)

MODULE_big = <%=ext_name%>
OBJS = $(patsubst %.c,%.o,$(wildcard src/*.c))

TESTS   = $(wildcard test/sql/*.sql)
REGRESS = $(patsubst test/sql/%.sql,%,$(TESTS))

all: concat

concat:
	echo > $(EXTENSION)--$(EXTVERSION).sql
	cat $(wildcard sql/*.sql) >> $(EXTENSION)--$(EXTVERSION).sql

REGRESS_OPTS = --inputdir=test --load-language=plpgsql
include $(PGXS)
