EXTENSION    = <%= extension_name %>
DATA         = $(wildcard *--*.sql)
DOCS         = $(wildcard doc/*.md)
TESTS        = $(wildcard test/sql/*.sql)
REGRESS      = $(patsubst test/sql/%.sql,%,$(TESTS))
REGRESS_OPTS = --inputdir=test --load-language=plpgsql
MODULE_big   = <%=extension_name%>
OBJS         = $(patsubst %.c,%.o,$(wildcard src/*.c))

PG_CONFIG ?= pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
